version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - eslog:/usr/share/elasticsearch/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # serve frontend

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - "14267"
      - "14268"
      - "14269"
      - "14250"
    depends_on:
      - elasticsearch
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200", "--es.timeout=0"]

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://localhost:9200
    ports:
      - "16686:16686"
    depends_on:
      - elasticsearch
      - jaeger-collector
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200", "--es.sniffer=false", "--log-level=debug" ]

  otel-collector:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" # service metrics for prometheus
      - "8889:8889" # otel metrics for prometheus
      - "55680" # accept trace data from otel-agent
    depends_on:
      - jaeger-collector

  otel-agent:
    image: otel/opentelemetry-collector-dev:latest
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "55678" # accept trace data from service
    depends_on:
      - otel-collector

  load-generator:
    image: golang:latest
    volumes:
      - ./main.go:/root/go/src/otel_test/main.go
      - ./go.mod:/root/go/src/otel_test/go.mod
    environment:
      - OTEL_AGENT_ENDPOINT=otel-agent:55678
      - GOPATH=/root/go
    command: bash -c "cd /root/go/src/otel_test && go get && go run ./main.go"
    depends_on:
      - otel-agent

volumes:
  esdata1:
    driver: local
  eslog:
    driver: local