receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:55678"
      http:

exporters:
  otlp:
    endpoint: "otel-collector:55680"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]