apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: observability
    component: prometheus
spec:
  selector:
    matchLabels:
      app: observability
      component: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: observability
        component: prometheus
    spec:
      containers:
        - image: prom/prometheus:v2.23.0
          name: prometheus
          imagePullPolicy: IfNotPresent
          args: ["--config.file=/etc/config/prometheus-config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: observability
    component: prometheus
spec:
  type: NodePort
  ports:
    - name: prometheus-front
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    component: prometheus